In [1]:
!pip install scikit-learn
import numpy as np
!pip install numpy
import pandas as pd
!pip install pandas

In [246]:
#Importing dataset
# 1.1 read data 
filename = 'NHANES_age_prediction.csv'
df = pd.read_csv(filename)
df.head(10)

SEQN age_group  RIDAGEYR  RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  \
0  73564.0     Adult      61.0       2.0     2.0    35.7   110.0     2.0   
1  73568.0     Adult      26.0       2.0     2.0    20.3    89.0     2.0   
2  73576.0     Adult      16.0       1.0     2.0    23.2    89.0     2.0   
3  73577.0     Adult      32.0       1.0     2.0    28.9   104.0     2.0   
4  73580.0     Adult      38.0       2.0     1.0    35.9   103.0     2.0   
5  73581.0     Adult      50.0       1.0     2.0    23.6   110.0     2.0   
6  73587.0     Adult      14.0       1.0     2.0    38.7    94.0     2.0   
7  73596.0     Adult      57.0       2.0     2.0    38.3   107.0     2.0   
8  73607.0    Senior      75.0       1.0     2.0    38.9    89.0     2.0   
9  73610.0     Adult      43.0       1.0     1.0    28.9    90.0     2.0   

   LBXGLT  LBXIN  
0   150.0  14.91  
1    80.0   3.85  
2    68.0   6.14  
3    84.0  16.15  
4    81.0  10.92  
5   100.0   6.08  
6   202.0  21.11  
7   164.0  20.93  
8   113.0  17.47  
9    95.0   3.24

In [247]:
names = list(df.columns)
print(names)

['SEQN', 'age_group', 'RIDAGEYR', 'RIAGENDR', 'PAQ605', 'BMXBMI', 'LBXGLU', 'DIQ010', 'LBXGLT', 'LBXIN']


In [248]:
types = df.dtypes
print(types)

SEQN         float64
age_group     object
RIDAGEYR     float64
RIAGENDR     float64
PAQ605       float64
BMXBMI       float64
LBXGLU       float64
DIQ010       float64
LBXGLT       float64
LBXIN        float64
dtype: object


In [254]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
for i in range(len(types)):
    if types[i]=='object':
        le.fit_transform(df[names[i]])
        df[names[i]] = le.transform(df[names[i]])

print('Successful')

Successful


In [255]:
types = df.dtypes
print(types)
data = df.values
print(data[:10])
#pd.get_dummies(data=df)

SEQN         float64
age_group      int32
RIDAGEYR     float64
RIAGENDR     float64
PAQ605       float64
BMXBMI       float64
LBXGLU       float64
DIQ010       float64
LBXGLT       float64
LBXIN        float64
dtype: object
[[7.3564e+04 0.0000e+00 6.1000e+01 2.0000e+00 2.0000e+00 3.5700e+01
  1.1000e+02 2.0000e+00 1.5000e+02 1.4910e+01]
 [7.3568e+04 0.0000e+00 2.6000e+01 2.0000e+00 2.0000e+00 2.0300e+01
  8.9000e+01 2.0000e+00 8.0000e+01 3.8500e+00]
 [7.3576e+04 0.0000e+00 1.6000e+01 1.0000e+00 2.0000e+00 2.3200e+01
  8.9000e+01 2.0000e+00 6.8000e+01 6.1400e+00]
 [7.3577e+04 0.0000e+00 3.2000e+01 1.0000e+00 2.0000e+00 2.8900e+01
  1.0400e+02 2.0000e+00 8.4000e+01 1.6150e+01]
 [7.3580e+04 0.0000e+00 3.8000e+01 2.0000e+00 1.0000e+00 3.5900e+01
  1.0300e+02 2.0000e+00 8.1000e+01 1.0920e+01]
 [7.3581e+04 0.0000e+00 5.0000e+01 1.0000e+00 2.0000e+00 2.3600e+01
  1.1000e+02 2.0000e+00 1.0000e+02 6.0800e+00]
 [7.3587e+04 0.0000e+00 1.4000e+01 1.0000e+00 2.0000e+00 3.8700e+01
  9.4000e+01 2.000

In [256]:
X = data[:,:-1]
y = data[:,-1]
print(X.shape)
print(y.shape)
print(y)

(2278, 9)
(2278,)
[14.91  3.85  6.14 ... 21.41  4.99  3.76]


In [257]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)
print(X_scaled[0])

[0.         0.         0.72058824 1.         0.16666667 0.38129496
 0.1374269  0.5        0.19503546]


In [236]:
from sklearn.preprocessing import Normalizer

norm = Normalizer()
df.iloc[:,1:-1] = norm.fit_transform(df.iloc[:,1:-1])
df


SEQN  age_group  RIDAGEYR  RIAGENDR    PAQ605    BMXBMI    LBXGLU  \
0     73564        0.0  0.306508  0.010049  0.010049  0.179382  0.552719   
1     73568        0.0  0.209371  0.016105  0.016105  0.163470  0.716692   
2     73576        0.0  0.138487  0.008655  0.017311  0.200806  0.770332   
3     73577        0.0  0.227758  0.007117  0.014235  0.205694  0.740214   
4     73580        0.0  0.269295  0.014173  0.007087  0.254413  0.729931   
...     ...        ...       ...       ...       ...       ...       ...   
2273  83711        0.0  0.283968  0.014946  0.014946  0.250340  0.747284   
2274  83712        0.0  0.256531  0.004205  0.008411  0.126163  0.391105   
2275  83713        0.0  0.204243  0.006007  0.012014  0.142369  0.618736   
2276  83718        0.0  0.386280  0.012876  0.012876  0.176401  0.579419   
2277  83727        0.0  0.165725  0.006374  0.012748  0.156164  0.688397   

        DIQ010    LBXGLT  LBXIN  
0     0.010049  0.753707  14.91  
1     0.016105  0.644217   3.85  
2     0.017311  0.588568   6.14  
3     0.014235  0.597865  16.15  
4     0.014173  0.574023  10.92  
...        ...       ...    ...  
2273  0.014946  0.545517   6.53  
2274  0.008411  0.874730  13.02  
2275  0.012014  0.744887  21.41  
2276  0.012876  0.695303   4.99  
2277  0.012748  0.688397   3.76  

[2278 rows x 10 columns]

In [258]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split \
(X_scaled,y,random_state=42)

In [259]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from math import sqrt


gnb = GaussianNB()
gnb.fit(X_train, y_train)
#gnb.paratical_fit(X_train,y_train)
y_pred = gnb.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("MAE test score: ",mean_absolute_error(y_test,y_pred))
print("RMSE test score: ",sqrt(mean_squared_error(y_test,y_pred)))

ValueError: Unknown label type: (array([  0.14,   1.02,   1.07, ...,  76.99,  79.75, 102.29]),)

In [207]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split \
(X_scaled,y,random_state=42)

In [208]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from math import sqrt


mnb = MultinomialNB()
mnb.fit(X_train, y_train)
y_pred = mnb.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("MAE test score: ",mean_absolute_error(y_test,y_pred))
print("RMSE test score: ",sqrt(mean_squared_error(y_test,y_pred)))

ValueError: Unknown label type: (array([14.67,  4.49,  5.12, ..., 17.92,  3.21, 21.85]),)

In [209]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from math import sqrt


bnb = BernoulliNB()
bnb.fit(X_train, y_train)
y_pred = bnb.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("MAE test score: ",mean_absolute_error(y_test,y_pred))
print("RMSE test score: ",sqrt(mean_squared_error(y_test,y_pred)))

ValueError: Unknown label type: (array([14.67,  4.49,  5.12, ..., 17.92,  3.21, 21.85]),)

In [27]:
from sklearn.naive_bayes import CategoricalNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from math import sqrt


CateNB = CategoricalNB()
CateNB.fit(X_train, y_train)
y_pred = CateNB.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("MAE test score: ",mean_absolute_error(y_test,y_pred))
print("RMSE test score: ",sqrt(mean_squared_error(y_test,y_pred)))

IndexError: index 1 is out of bounds for axis 1 with size 1

In [211]:
from sklearn.naive_bayes import ComplementNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from math import sqrt


ComplementNB = ComplementNB(force_alpha=True)
ComplementNB.fit(X_train, y_train)
y_pred = ComplementNB.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("MAE test score: ",mean_absolute_error(y_test,y_pred))
print("RMSE test score: ",sqrt(mean_squared_error(y_test,y_pred)))

ValueError: Unknown label type: (array([14.67,  4.49,  5.12, ..., 17.92,  3.21, 21.85]),)

In [29]:
from sklearn.naive_bayes import ComplementNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from math import sqrt


ComplementNB = ComplementNB(force_alpha=True)
ComplementNB.fit(X_train, y_train)
y_pred = ComplementNB.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("MAE test score: ",mean_absolute_error(y_test,y_pred))
print("RMSE test score: ",sqrt(mean_squared_error(y_test,y_pred)))

[[76 47]
 [29 40]]
              precision    recall  f1-score   support

         0.0       0.72      0.62      0.67       123
         1.0       0.46      0.58      0.51        69

    accuracy                           0.60       192
   macro avg       0.59      0.60      0.59       192
weighted avg       0.63      0.60      0.61       192

MAE test score:  0.3958333333333333
RMSE test score:  0.6291528696058958


In [30]:
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

clf = tree.DecisionTreeRegressor(random_state=0)
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[86 37]
 [23 46]]
              precision    recall  f1-score   support

         0.0       0.79      0.70      0.74       123
         1.0       0.55      0.67      0.61        69

    accuracy                           0.69       192
   macro avg       0.67      0.68      0.67       192
weighted avg       0.70      0.69      0.69       192

